name: Build Static Rahgosha

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install
        run: npm install

      - name: Build Static
        run: npm run build

      - name: Zip Output
        run: |
          cd out
          zip -r ../rahgosha-static.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rahgosha-static
          path: rahgosha-static.zip
